manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kot149
      url-base: https://github.com/kot149
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
    - name: mjmjm0101
      url-base: https://github.com/mjmjm0101
    - name: ssbb
      url-base: https://github.com/ssbb
    - name: oleksandrmaslov
      url-base: https://github.com/oleksandrmaslov
      
  projects:
    # https://github.com/zmkfirmware/zmk
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml

    # https://github.com/kumamuk-git/zmk-pmw3610-driver
    - name: zmk-pmw3610-driver
      remote: kumamuk-git
      revision: main

    - name: zmk-listeners
      remote: ssbb
      revision: v1
      path: modules/zmk-listeners

    - name: zmk-mouse-gesture
      remote: kot149
      revision: v1
      path: modules/zmk-mouse-gesture

    # https://github.com/kot149/zmk-layout-shift
    - name: zmk-layout-shift
      remote: kot149
      revision: v1
      path: modules/zmk-layout-shift

    - name: zmk-pointing-acceleration
      remote: oleksandrmaslov
      revision: main
      path: modules/zmk-pointing-acceleration

    - name: zmk-input-processor-scroll-inertia
      remote: mjmjm0101
      revision: f7dadef
      path: modules/zmk-input-processor-scroll-inertia

  self:
    path: config
